In [7]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Reading the data

In [3]:
b = pd.read_csv('bank.csv',sep = ";")
b.head()

age          job  marital  education  ... pdays  previous poutcome   y
0   30   unemployed  married    primary  ...    -1         0  unknown  no
1   33     services  married  secondary  ...   339         4  failure  no
2   35   management   single   tertiary  ...   330         1  failure  no
3   30   management  married   tertiary  ...    -1         0  unknown  no
4   59  blue-collar  married  secondary  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [4]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        4521 non-null   int64 
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64 
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64 
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64 
 12  campaign   4521 non-null   int64 
 13  pdays      4521 non-null   int64 
 14  previous   4521 non-null   int64 
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB


# Total missing values for each feature

In [5]:
print (b.isnull().sum())

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64


#Label Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()

b.loc[:,"job"] = labelencoder.fit_transform(b.loc[:,"job"])
b.loc[:,"marital"] = labelencoder.fit_transform(b.loc[:,"marital"])
b.loc[:,"education"] = labelencoder.fit_transform(b.loc[:,"education"])
b.loc[:,"default"] = labelencoder.fit_transform(b.loc[:,"default"])
b.loc[:,"housing"] = labelencoder.fit_transform(b.loc[:,"housing"])
b.loc[:,"loan"] = labelencoder.fit_transform(b.loc[:,"loan"] )
b.loc[:,"contact"] = labelencoder.fit_transform(b.loc[:,"contact"])
b.loc[:,"month"] = labelencoder.fit_transform(b.loc[:,"month"])
b.loc[:,"poutcome"] = labelencoder.fit_transform(b.loc[:,"poutcome"])
b.loc[:,"y"] = labelencoder.fit_transform(b.loc[:,"y"])

# One Hot Encoding

In [9]:
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder(drop="first")
b = onehotencoder.fit_transform(b).toarray()
b = b[:, 1:]

In [10]:
b = pd.DataFrame(b)
b.head()

0     1     2     3     4     5     ...  3696  3697  3698  3699  3700  3701
0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   1.0   0.0
1   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
2   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
3   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   1.0   0.0
4   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   1.0   0.0

[5 rows x 3702 columns]

In [11]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Columns: 3702 entries, 0 to 3701
dtypes: float64(3702)
memory usage: 127.7 MB


#Finding and removing outliers

In [13]:
#Discover outliers with mathematical function - Z-Score-
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(b))
#print(z)
#print(z.shape)

#Working with Outliers: Correcting, Removing
#ad_o = ad[(z > 3).all(axis=1)]
b_o = b[(z < 3).all(axis=1)]
b_i = b[~((z < 3).all(axis=1))]


print("Original Dataset Shape: ",b.shape)
print("Outlier in the Dataset Shape: ",b_o.shape)
print("Without Outlier in the Dataset Shape: ",b_i.shape)

Original Dataset Shape:  (4521, 3702)
Outlier in the Dataset Shape:  (0, 3702)
Without Outlier in the Dataset Shape:  (4521, 3702)


In [14]:
#Using IQR Score

Q1 = b.quantile(0.25)
Q3 = b.quantile(0.75)
IQR = Q3 - Q1
#print(IQR)


b_out = b[~((b < (Q1 - 1.5 * IQR)) |(b > (Q3 + 1.5 * IQR))).any(axis=1)]
b_in = b[((b < (Q1 - 1.5 * IQR)) |(b > (Q3 + 1.5 * IQR))).any(axis=1)]

print("Original Dataset Shape: ",b.shape)
print("Outlier in the Dataset Shape: ",b_out.shape)
print("Without Outlier in the Dataset Shape: ",b_in.shape)

Original Dataset Shape:  (4521, 3702)
Outlier in the Dataset Shape:  (0, 3702)
Without Outlier in the Dataset Shape:  (4521, 3702)


In [16]:
b_in.head()

0     1     2     3     4     5     ...  3696  3697  3698  3699  3700  3701
0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   1.0   0.0
1   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
2   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
3   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   1.0   0.0
4   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   1.0   0.0

[5 rows x 3702 columns]

In [17]:
#Creating Train and Test datasets
X = b_in.iloc[:,0:3701]
y = b_in.iloc[:,3701]

In [20]:
print(X.shape,y.shape)

(4521, 3701) (4521,)


In [18]:
X.head()

0     1     2     3     4     5     ...  3695  3696  3697  3698  3699  3700
0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   1.0
1   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
2   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
3   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   1.0
4   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   1.0

[5 rows x 3701 columns]

In [19]:
y.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: 3701, dtype: float64

#Train and Test Spiltting

In [22]:

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2)
print( X_train.shape, y_train.shape)
print( X_test.shape, y_test.shape)

(3616, 3701) (3616,)
(905, 3701) (905,)


#SVM

In [25]:
# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

print("Accuracy score: {:0.3}".format(accuracy_score(y_test,y_pred)))

Accuracy score: 0.878


In [26]:
import warnings
warnings.filterwarnings("ignore")

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix \n")
print(cm)
print("\n")
# classification report for precision, recall f1-score and accuracy
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred)
print('Classification report : \n',matrix)

Confusion Matrix 

[[787   9]
 [101   8]]


Classification report : 
               precision    recall  f1-score   support

         0.0       0.89      0.99      0.93       796
         1.0       0.47      0.07      0.13       109

    accuracy                           0.88       905
   macro avg       0.68      0.53      0.53       905
weighted avg       0.84      0.88      0.84       905



## Using k-Fold Cross Validation

In [29]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)

print(accuracies)
print(accuracies.mean())
print(accuracies.std())


[0.90055249 0.89779006 0.90883978 0.89226519 0.88674033 0.90055249
 0.90027701 0.90304709 0.88919668 0.88919668]
0.8968457783015257
0.006801294368386098


## Using Grid Search 

In [27]:

# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

print(best_accuracy)
print(best_parameters)

0.8965680047749498
{'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}


#Building Multiple Models

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier


from sklearn.metrics import confusion_matrix,accuracy_score

In [33]:
for mod in [LogisticRegression(),KNeighborsClassifier(),SVC(),RandomForestClassifier(),GaussianNB(),DecisionTreeClassifier(),
           BaggingClassifier(KNeighborsClassifier(),max_samples=0.5, max_features=0.5),
           ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0),
           AdaBoostClassifier(n_estimators=100),GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0)]:
	mod.fit(X_train,y_train)
	y_pred = mod.predict(X_test)
	print("="*80)
	print(mod)
	print("-"*80)
	print("Accuracy score: {:0.3}".format(accuracy_score(y_test,y_pred)))

	print("Confusion Matrix:")
	print(confusion_matrix(y_test,y_pred))
	print()

LogisticRegression()
--------------------------------------------------------------------------------
Accuracy score: 0.88
Confusion Matrix:
[[784  12]
 [ 97  12]]

KNeighborsClassifier()
--------------------------------------------------------------------------------
Accuracy score: 0.871
Confusion Matrix:
[[784  12]
 [105   4]]

SVC()
--------------------------------------------------------------------------------
Accuracy score: 0.878
Confusion Matrix:
[[787   9]
 [101   8]]

RandomForestClassifier()
--------------------------------------------------------------------------------
Accuracy score: 0.881
Confusion Matrix:
[[792   4]
 [104   5]]

GaussianNB()
--------------------------------------------------------------------------------
Accuracy score: 0.727
Confusion Matrix:
[[615 181]
 [ 66  43]]

DecisionTreeClassifier()
--------------------------------------------------------------------------------
Accuracy score: 0.854
Confusion Matrix:
[[760  36]
 [ 96  13]]

BaggingClassifier(

#Using VotingClassifier with hard voting

In [35]:
from sklearn.ensemble import VotingClassifier
lr = LogisticRegression()
kn = KNeighborsClassifier()
svc = SVC()
rf = RandomForestClassifier()
gb = GaussianNB()
dt = DecisionTreeClassifier()
bg = BaggingClassifier(KNeighborsClassifier(),max_samples=0.5, max_features=0.5)
et = ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)
ab = AdaBoostClassifier(n_estimators=100)
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0)

eclf1 = VotingClassifier(estimators=[
         ('lr', lr),('kn',kn), ('rf', rf),('svc',svc), ('gb', gb),('dt',dt),('bg',bg),('et',et),('ab',ab),('gbc',gbc)], voting='hard')

eclf1 = eclf1.fit(X_train,y_train)


y_pred = eclf1.predict(X_test)
print("Accuracy score: {:0.3}".format(accuracy_score(y_test,y_pred)))

print(eclf1.get_params(deep=True))

Accuracy score: 0.878
{'estimators': [('lr', LogisticRegression()), ('kn', KNeighborsClassifier()), ('rf', RandomForestClassifier()), ('svc', SVC()), ('gb', GaussianNB()), ('dt', DecisionTreeClassifier()), ('bg', BaggingClassifier(base_estimator=KNeighborsClassifier(), max_features=0.5,
                  max_samples=0.5)), ('et', ExtraTreesClassifier(n_estimators=10, random_state=0)), ('ab', AdaBoostClassifier(n_estimators=100)), ('gbc', GradientBoostingClassifier(learning_rate=1.0, max_depth=1, random_state=0))], 'flatten_transform': True, 'n_jobs': None, 'verbose': False, 'voting': 'hard', 'weights': None, 'lr': LogisticRegression(), 'kn': KNeighborsClassifier(), 'rf': RandomForestClassifier(), 'svc': SVC(), 'gb': GaussianNB(), 'dt': DecisionTreeClassifier(), 'bg': BaggingClassifier(base_estimator=KNeighborsClassifier(), max_features=0.5,
                  max_samples=0.5), 'et': ExtraTreesClassifier(n_estimators=10, random_state=0), 'ab': AdaBoostClassifier(n_estimators=100), 'gbc':

#Using VotingClassifier with soft voting

In [37]:

from sklearn.ensemble import VotingClassifier

lr = LogisticRegression()
kn = KNeighborsClassifier()
svc = SVC()
rf = RandomForestClassifier()
gb = GaussianNB()
dt = DecisionTreeClassifier()
bg = BaggingClassifier(KNeighborsClassifier(),max_samples=0.5, max_features=0.5)
et = ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)
ab = AdaBoostClassifier(n_estimators=100)
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0)

eclf1 = VotingClassifier(estimators=[
          ('lr', lr),('kn',kn), ('rf', rf),('svc',svc), ('gb', gb),('dt',dt),('bg',bg),('et',et),('ab',ab),('gbc',gbc)], voting='soft')

eclf1 = eclf1.fit(X_train,y_train)

In [45]:
print(eclf1.score)

print(eclf1.get_params(deep=True))

<bound method ClassifierMixin.score of VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('kn', KNeighborsClassifier()),
                             ('rf', RandomForestClassifier()), ('svc', SVC()),
                             ('gb', GaussianNB()),
                             ('dt', DecisionTreeClassifier()),
                             ('bg',
                              BaggingClassifier(base_estimator=KNeighborsClassifier(),
                                                max_features=0.5,
                                                max_samples=0.5)),
                             ('et',
                              ExtraTreesClassifier(n_estimators=10,
                                                   random_state=0)),
                             ('ab', AdaBoostClassifier(n_estimators=100)),
                             ('gbc',
                              GradientBoostingClassifier(learning_rate=1.0,
                               