In [32]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Reading the data

In [33]:
b = pd.read_csv('bank.csv',sep = ";")
b.head()

age          job  marital  education  ... pdays  previous poutcome   y
0   30   unemployed  married    primary  ...    -1         0  unknown  no
1   33     services  married  secondary  ...   339         4  failure  no
2   35   management   single   tertiary  ...   330         1  failure  no
3   30   management  married   tertiary  ...    -1         0  unknown  no
4   59  blue-collar  married  secondary  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [34]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        4521 non-null   int64 
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64 
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64 
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64 
 12  campaign   4521 non-null   int64 
 13  pdays      4521 non-null   int64 
 14  previous   4521 non-null   int64 
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB


# Total missing values for each feature

In [35]:
print (b.isnull().sum())

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64


#Label Encoding

##Finding Categorical Variables

In [36]:
cat_variables = [i for i in b.columns if b.dtypes[i] == 'object']
cat_variables

['job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'month',
 'poutcome',
 'y']

In [37]:
cat_variables_index = [i for i in range(len(b.columns)) if b.dtypes[i] == 'object']
cat_variables_index

[1, 2, 3, 4, 6, 7, 8, 10, 15, 16]

In [39]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
for i in range(len(b.columns)):
  b.iloc[:,i] = labelencoder.fit_transform(b.iloc[:,i])

In [40]:
b.head()

age  job  marital  education  ...  pdays  previous  poutcome  y
0   11   10        1          0  ...      0         0         3  0
1   14    7        1          1  ...    228         4         0  0
2   16    4        2          2  ...    219         1         0  0
3   11    4        1          2  ...      0         0         3  0
4   40    1        1          1  ...      0         0         3  0

[5 rows x 17 columns]

# One Hot Encoding

In [41]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import numpy as np


onehotencoder = OneHotEncoder()

ct = ColumnTransformer([('one_hot_encoder', OneHotEncoder(), cat_variables_index)], remainder='passthrough')
b = np.array(ct.fit_transform(b), dtype=np.float)

In [42]:
b = pd.DataFrame(b)
b.head()

0    1    2    3    4    5   ...      47    48     49   50     51   52
0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1475.0  18.0   75.0  0.0    0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  ...  2030.0  10.0  216.0  0.0  228.0  4.0
2  0.0  0.0  0.0  0.0  1.0  0.0  ...  1303.0  15.0  181.0  0.0  219.0  1.0
3  0.0  0.0  0.0  0.0  1.0  0.0  ...  1352.0   2.0  195.0  3.0    0.0  0.0
4  0.0  1.0  0.0  0.0  0.0  0.0  ...   274.0   4.0  222.0  0.0    0.0  0.0

[5 rows x 53 columns]

In [43]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 53 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       4521 non-null   float64
 1   1       4521 non-null   float64
 2   2       4521 non-null   float64
 3   3       4521 non-null   float64
 4   4       4521 non-null   float64
 5   5       4521 non-null   float64
 6   6       4521 non-null   float64
 7   7       4521 non-null   float64
 8   8       4521 non-null   float64
 9   9       4521 non-null   float64
 10  10      4521 non-null   float64
 11  11      4521 non-null   float64
 12  12      4521 non-null   float64
 13  13      4521 non-null   float64
 14  14      4521 non-null   float64
 15  15      4521 non-null   float64
 16  16      4521 non-null   float64
 17  17      4521 non-null   float64
 18  18      4521 non-null   float64
 19  19      4521 non-null   float64
 20  20      4521 non-null   float64
 21  21      4521 non-null   float64
 22  

#Finding and removing outliers

In [44]:
#Discover outliers with mathematical function - Z-Score-
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(b))
#print(z)
#print(z.shape)

#Working with Outliers: Correcting, Removing
#ad_o = ad[(z > 3).all(axis=1)]
b_o = b[(z < 3).all(axis=1)]
b_i = b[~((z < 3).all(axis=1))]


print("Original Dataset Shape: ",b.shape)
print("Outlier in the Dataset Shape: ",b_o.shape)
print("Without Outlier in the Dataset Shape: ",b_i.shape)

Original Dataset Shape:  (4521, 53)
Outlier in the Dataset Shape:  (1834, 53)
Without Outlier in the Dataset Shape:  (2687, 53)


##Train and Test Spiltting

In [45]:
#Creating Train and Test datasets
X = b_i.iloc[:,0:52]
y = b_i.iloc[:,52]

In [46]:
print(X.shape,y.shape)

(2687, 52) (2687,)


In [47]:
X.head()

0    1    2    3    4    5   ...    46      47    48     49   50     51
0  0.0  0.0  0.0  0.0  0.0  0.0  ...  11.0  1475.0  18.0   75.0  0.0    0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  ...  14.0  2030.0  10.0  216.0  0.0  228.0
2  0.0  0.0  0.0  0.0  1.0  0.0  ...  16.0  1303.0  15.0  181.0  0.0  219.0
5  0.0  0.0  0.0  0.0  1.0  0.0  ...  16.0   934.0  22.0  137.0  1.0  109.0
6  0.0  0.0  0.0  0.0  0.0  0.0  ...  17.0   569.0  13.0  337.0  0.0  219.0

[5 rows x 52 columns]

In [48]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2)
print( X_train.shape, y_train.shape)
print( X_test.shape, y_test.shape)

(2149, 52) (2149,)
(538, 52) (538,)


##SVM

In [49]:
# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

print("Accuracy score: {:0.3}".format(accuracy_score(y_test,y_pred)))

Accuracy score: 0.82


In [50]:
import warnings
warnings.filterwarnings("ignore")

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix \n")
print(cm)
print("\n")
# classification report for precision, recall f1-score and accuracy
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred)
print('Classification report : \n',matrix)

Confusion Matrix 

[[398   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 10  43   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  6  20   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  7   9   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  5  11   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   6   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   3   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  2   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0   0   0   0   0   0 

#Removing Outliers Using IQR Score

In [51]:
#Using IQR Score

Q1 = b.quantile(0.25)
Q3 = b.quantile(0.75)
IQR = Q3 - Q1
#print(IQR)


b_out = b[~((b < (Q1 - 1.5 * IQR)) |(b > (Q3 + 1.5 * IQR))).any(axis=1)]
b_in = b[((b < (Q1 - 1.5 * IQR)) |(b > (Q3 + 1.5 * IQR))).any(axis=1)]

print("Original Dataset Shape: ",b.shape)
print("Outlier in the Dataset Shape: ",b_out.shape)
print("Without Outlier in the Dataset Shape: ",b_in.shape)

Original Dataset Shape:  (4521, 53)
Outlier in the Dataset Shape:  (0, 53)
Without Outlier in the Dataset Shape:  (4521, 53)


In [52]:
b_in.head()

0    1    2    3    4    5   ...      47    48     49   50     51   52
0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1475.0  18.0   75.0  0.0    0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  ...  2030.0  10.0  216.0  0.0  228.0  4.0
2  0.0  0.0  0.0  0.0  1.0  0.0  ...  1303.0  15.0  181.0  0.0  219.0  1.0
3  0.0  0.0  0.0  0.0  1.0  0.0  ...  1352.0   2.0  195.0  3.0    0.0  0.0
4  0.0  1.0  0.0  0.0  0.0  0.0  ...   274.0   4.0  222.0  0.0    0.0  0.0

[5 rows x 53 columns]

In [53]:
#Creating Train and Test datasets
X = b_in.iloc[:,0:52]
y = b_in.iloc[:,52]

In [54]:
print(X.shape,y.shape)

(4521, 52) (4521,)


In [55]:
X.head()

0    1    2    3    4    5   ...    46      47    48     49   50     51
0  0.0  0.0  0.0  0.0  0.0  0.0  ...  11.0  1475.0  18.0   75.0  0.0    0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  ...  14.0  2030.0  10.0  216.0  0.0  228.0
2  0.0  0.0  0.0  0.0  1.0  0.0  ...  16.0  1303.0  15.0  181.0  0.0  219.0
3  0.0  0.0  0.0  0.0  1.0  0.0  ...  11.0  1352.0   2.0  195.0  3.0    0.0
4  0.0  1.0  0.0  0.0  0.0  0.0  ...  40.0   274.0   4.0  222.0  0.0    0.0

[5 rows x 52 columns]

In [56]:
y.head()

0    0.0
1    4.0
2    1.0
3    0.0
4    0.0
Name: 52, dtype: float64

##Train and Test Spiltting

In [57]:

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2)
print( X_train.shape, y_train.shape)
print( X_test.shape, y_test.shape)

(3616, 52) (3616,)
(905, 52) (905,)


##SVM

In [58]:
# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

print("Accuracy score: {:0.3}".format(accuracy_score(y_test,y_pred)))

Accuracy score: 0.855


In [59]:
import warnings
warnings.filterwarnings("ignore")

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix \n")
print(cm)
print("\n")
# classification report for precision, recall f1-score and accuracy
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred)
print('Classification report : \n',matrix)

Confusion Matrix 

[[728   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 20  46   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 11  24   0   0   0   0   0   0   0   0   0   0   0   0]
 [  5  16   0   0   0   0   0   0   0   0   0   0   0   0]
 [  3  15   0   0   0   0   0   0   0   0   0   0   0   0]
 [  5   3   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   7   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   5   0   0   0   0   0   0   0   0   0   0   0   0]
 [  3   4   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0   0   0   0   0   0   0   0]]


Classification report : 
               precision    recall  f1-score   support

         0.0       0.93      1.00      0.97       728
         1.0     

### Using k-Fold Cross Validation

In [62]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)

print(accuracies)
print("Mean accuracy: ",accuracies.mean())
print("Standard deviation of accuracy: ",accuracies.std())


[0.85359116 0.87292818 0.85911602 0.87016575 0.86464088 0.86740331
 0.87257618 0.86703601 0.86980609 0.86149584]
Mean accuracy:  0.8658759431291226
Standard deviation of accuracy:  0.005911660592886756


##Building Multiple Models

In [63]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier


from sklearn.metrics import confusion_matrix,accuracy_score

In [64]:
for mod in [LogisticRegression(),KNeighborsClassifier(),SVC(),RandomForestClassifier(),GaussianNB(),DecisionTreeClassifier(),
           BaggingClassifier(KNeighborsClassifier(),max_samples=0.5, max_features=0.5),
           ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0),
           AdaBoostClassifier(n_estimators=100),GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0)]:
	mod.fit(X_train,y_train)
	y_pred = mod.predict(X_test)
	print("="*80)
	print(mod)
	print("-"*80)
	print("Accuracy score: {:0.3}".format(accuracy_score(y_test,y_pred)))

	print("Confusion Matrix:")
	print(confusion_matrix(y_test,y_pred))
	print()

LogisticRegression()
--------------------------------------------------------------------------------
Accuracy score: 0.877
Confusion Matrix:
[[728   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1  65   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1  33   1   0   0   0   0   0   0   0   0   0   0   0]
 [  0  21   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1  17   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   7   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   6   1   0   0   0   0   0   0   0   0   0   0   0]
 [  0   6   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   6   1   0   0   0   0   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0   0   0]]

KNeighborsClassifier()
-------

##Using VotingClassifier with hard voting

In [65]:
from sklearn.ensemble import VotingClassifier
lr = LogisticRegression()
kn = KNeighborsClassifier()
svc = SVC()
rf = RandomForestClassifier()
gb = GaussianNB()
dt = DecisionTreeClassifier()
bg = BaggingClassifier(KNeighborsClassifier(),max_samples=0.5, max_features=0.5)
et = ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)
ab = AdaBoostClassifier(n_estimators=100)
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0)

eclf1 = VotingClassifier(estimators=[
         ('lr', lr),('kn',kn), ('rf', rf),('svc',svc), ('gb', gb),('dt',dt),('bg',bg),('et',et),('ab',ab),('gbc',gbc)], voting='hard')

eclf1 = eclf1.fit(X_train,y_train)


y_pred = eclf1.predict(X_test)
print("Accuracy score: {:0.3}".format(accuracy_score(y_test,y_pred)))

print(eclf1.get_params(deep=True))

Accuracy score: 0.866
{'estimators': [('lr', LogisticRegression()), ('kn', KNeighborsClassifier()), ('rf', RandomForestClassifier()), ('svc', SVC()), ('gb', GaussianNB()), ('dt', DecisionTreeClassifier()), ('bg', BaggingClassifier(base_estimator=KNeighborsClassifier(), max_features=0.5,
                  max_samples=0.5)), ('et', ExtraTreesClassifier(n_estimators=10, random_state=0)), ('ab', AdaBoostClassifier(n_estimators=100)), ('gbc', GradientBoostingClassifier(learning_rate=1.0, max_depth=1, random_state=0))], 'flatten_transform': True, 'n_jobs': None, 'verbose': False, 'voting': 'hard', 'weights': None, 'lr': LogisticRegression(), 'kn': KNeighborsClassifier(), 'rf': RandomForestClassifier(), 'svc': SVC(), 'gb': GaussianNB(), 'dt': DecisionTreeClassifier(), 'bg': BaggingClassifier(base_estimator=KNeighborsClassifier(), max_features=0.5,
                  max_samples=0.5), 'et': ExtraTreesClassifier(n_estimators=10, random_state=0), 'ab': AdaBoostClassifier(n_estimators=100), 'gbc':

##Using VotingClassifier with soft voting

In [66]:

from sklearn.ensemble import VotingClassifier

lr = LogisticRegression()
kn = KNeighborsClassifier()
svc = SVC()
rf = RandomForestClassifier()
gb = GaussianNB()
dt = DecisionTreeClassifier()
bg = BaggingClassifier(KNeighborsClassifier(),max_samples=0.5, max_features=0.5)
et = ExtraTreesClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)
ab = AdaBoostClassifier(n_estimators=100)
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0)

eclf1 = VotingClassifier(estimators=[
          ('lr', lr),('kn',kn), ('rf', rf),('svc',svc), ('gb', gb),('dt',dt),('bg',bg),('et',et),('ab',ab),('gbc',gbc)], voting='soft')

eclf1 = eclf1.fit(X_train,y_train)

In [67]:
print(eclf1.score)

print(eclf1.get_params(deep=True))

<bound method ClassifierMixin.score of VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('kn', KNeighborsClassifier()),
                             ('rf', RandomForestClassifier()), ('svc', SVC()),
                             ('gb', GaussianNB()),
                             ('dt', DecisionTreeClassifier()),
                             ('bg',
                              BaggingClassifier(base_estimator=KNeighborsClassifier(),
                                                max_features=0.5,
                                                max_samples=0.5)),
                             ('et',
                              ExtraTreesClassifier(n_estimators=10,
                                                   random_state=0)),
                             ('ab', AdaBoostClassifier(n_estimators=100)),
                             ('gbc',
                              GradientBoostingClassifier(learning_rate=1.0,
                               

### Using Grid Search 

In [ ]:
# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

classifier = SVC(kernel = 'rbf', random_state = 0)

In [ ]:
# Applying Grid Search to find the best model and the best parameters
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

print(best_accuracy)
print(best_parameters)