In [15]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")



#Loading Data

In [17]:
cancer = pd.read_csv('cancer.csv')

In [18]:
cancer.head()

V1     V2      V3      V4  ...     V28     V29      V30  Class
0  17.99  10.38  122.80  1001.0  ...  0.2654  0.4601  0.11890      2
1  20.57  17.77  132.90  1326.0  ...  0.1860  0.2750  0.08902      2
2  19.69  21.25  130.00  1203.0  ...  0.2430  0.3613  0.08758      2
3  11.42  20.38   77.58   386.1  ...  0.2575  0.6638  0.17300      2
4  20.29  14.34  135.10  1297.0  ...  0.1625  0.2364  0.07678      2

[5 rows x 31 columns]

In [19]:
cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      569 non-null    float64
 1   V2      569 non-null    float64
 2   V3      569 non-null    float64
 3   V4      569 non-null    float64
 4   V5      569 non-null    float64
 5   V6      569 non-null    float64
 6   V7      569 non-null    float64
 7   V8      569 non-null    float64
 8   V9      569 non-null    float64
 9   V10     569 non-null    float64
 10  V11     569 non-null    float64
 11  V12     569 non-null    float64
 12  V13     569 non-null    float64
 13  V14     569 non-null    float64
 14  V15     569 non-null    float64
 15  V16     569 non-null    float64
 16  V17     569 non-null    float64
 17  V18     569 non-null    float64
 18  V19     569 non-null    float64
 19  V20     569 non-null    float64
 20  V21     569 non-null    float64
 21  V22     569 non-null    float64
 22  V2

In [20]:
cancer['Class'].value_counts()

1    357
2    212
Name: Class, dtype: int64

In [21]:
X = cancer.drop(['Class'],axis=1)

In [22]:
y = cancer['Class']

#Train And Test Splitting

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(455, 30) (114, 30) (455,) (114,)


#Models

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from xgboost import  XGBClassifier 

from sklearn.metrics import confusion_matrix,classification_report

In [28]:
Model_list = [LogisticRegression(),KNeighborsClassifier(),SVC(),DecisionTreeClassifier()]

NB_Model_list = [GaussianNB(),MultinomialNB(),ComplementNB(),BernoulliNB()]

ensemble_Model_list = [BaggingClassifier(),GradientBoostingClassifier(),AdaBoostClassifier(),RandomForestClassifier(),ExtraTreesClassifier()]

In [36]:
for mod in range(len(Model_list)):
  model = Model_list[mod]
  
  model.fit(X_train,y_train)

  y_train_pred = model.predict(X_train)
  print("Model Used : ",model)
  print("=======================================================================")
  print("Metrics on Train samples")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
  print("classification_report: \n",classification_report(y_train,y_train_pred))
  print("============================================================== ")

  y_test_pred = model.predict(X_test)

  print("Metrics on Test samples ")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
  print("classification_report: \n",classification_report(y_test,y_test_pred))
  print("============================================================== ")
  print("=======================================================================")

Model Used :  LogisticRegression()
Metrics on Train samples
confusion_matrix: 
 [[278   8]
 [ 15 154]]
classification_report: 
               precision    recall  f1-score   support

           1       0.95      0.97      0.96       286
           2       0.95      0.91      0.93       169

    accuracy                           0.95       455
   macro avg       0.95      0.94      0.95       455
weighted avg       0.95      0.95      0.95       455

Metrics on Test samples 
confusion_matrix: 
 [[70  1]
 [ 3 40]]
classification_report: 
               precision    recall  f1-score   support

           1       0.96      0.99      0.97        71
           2       0.98      0.93      0.95        43

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

Model Used :  KNeighborsClassifier()
Metrics on Train samples
confusion_matrix: 
 [[281   5]
 [ 22 147]]
classification_report: 


In [37]:
for mod in range(len(NB_Model_list)):
  model = NB_Model_list[mod]
  
  
  model.fit(X_train,y_train)

  y_train_pred = model.predict(X_train)
  print("Model Used : ",model)
  print("=======================================================================")
  print("Metrics on Train samples")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
  print("classification_report: \n",classification_report(y_train,y_train_pred))
  print("============================================================== ")

  y_test_pred = model.predict(X_test)

  print("Metrics on Test samples ")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
  print("classification_report: \n",classification_report(y_test,y_test_pred))
  print("============================================================== ")
  print("=======================================================================")

Model Used :  GaussianNB()
Metrics on Train samples
confusion_matrix: 
 [[277   9]
 [ 20 149]]
classification_report: 
               precision    recall  f1-score   support

           1       0.93      0.97      0.95       286
           2       0.94      0.88      0.91       169

    accuracy                           0.94       455
   macro avg       0.94      0.93      0.93       455
weighted avg       0.94      0.94      0.94       455

Metrics on Test samples 
confusion_matrix: 
 [[71  0]
 [ 3 40]]
classification_report: 
               precision    recall  f1-score   support

           1       0.96      1.00      0.98        71
           2       1.00      0.93      0.96        43

    accuracy                           0.97       114
   macro avg       0.98      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

Model Used :  MultinomialNB()
Metrics on Train samples
confusion_matrix: 
 [[276  10]
 [ 42 127]]
classification_report: 
               

In [38]:
for mod in range(len(ensemble_Model_list)):
  model = ensemble_Model_list[mod]
  
  
  model.fit(X_train,y_train)

  y_train_pred = model.predict(X_train)
  print("Model Used : ",model)
  print("=======================================================================")
  print("Metrics on Train samples")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
  print("classification_report: \n",classification_report(y_train,y_train_pred))
  print("============================================================== ")

  y_test_pred = model.predict(X_test)

  print("Metrics on Test samples ")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
  print("classification_report: \n",classification_report(y_test,y_test_pred))
  print("============================================================== ")
  print("=======================================================================")

Model Used :  BaggingClassifier()
Metrics on Train samples
confusion_matrix: 
 [[286   0]
 [  3 166]]
classification_report: 
               precision    recall  f1-score   support

           1       0.99      1.00      0.99       286
           2       1.00      0.98      0.99       169

    accuracy                           0.99       455
   macro avg       0.99      0.99      0.99       455
weighted avg       0.99      0.99      0.99       455

Metrics on Test samples 
confusion_matrix: 
 [[69  2]
 [ 3 40]]
classification_report: 
               precision    recall  f1-score   support

           1       0.96      0.97      0.97        71
           2       0.95      0.93      0.94        43

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

Model Used :  GradientBoostingClassifier()
Metrics on Train samples
confusion_matrix: 
 [[286   0]
 [  0 169]]
classification_repo