In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

#Loading Data

In [3]:
cancer = pd.read_csv('cancer.csv')

In [3]:
cancer.head()

V1     V2      V3      V4  ...     V28     V29      V30  Class
0  17.99  10.38  122.80  1001.0  ...  0.2654  0.4601  0.11890      2
1  20.57  17.77  132.90  1326.0  ...  0.1860  0.2750  0.08902      2
2  19.69  21.25  130.00  1203.0  ...  0.2430  0.3613  0.08758      2
3  11.42  20.38   77.58   386.1  ...  0.2575  0.6638  0.17300      2
4  20.29  14.34  135.10  1297.0  ...  0.1625  0.2364  0.07678      2

[5 rows x 31 columns]

In [4]:
cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      569 non-null    float64
 1   V2      569 non-null    float64
 2   V3      569 non-null    float64
 3   V4      569 non-null    float64
 4   V5      569 non-null    float64
 5   V6      569 non-null    float64
 6   V7      569 non-null    float64
 7   V8      569 non-null    float64
 8   V9      569 non-null    float64
 9   V10     569 non-null    float64
 10  V11     569 non-null    float64
 11  V12     569 non-null    float64
 12  V13     569 non-null    float64
 13  V14     569 non-null    float64
 14  V15     569 non-null    float64
 15  V16     569 non-null    float64
 16  V17     569 non-null    float64
 17  V18     569 non-null    float64
 18  V19     569 non-null    float64
 19  V20     569 non-null    float64
 20  V21     569 non-null    float64
 21  V22     569 non-null    float64
 22  V2

In [5]:
cancer['Class'].value_counts()

1    357
2    212
Name: Class, dtype: int64

In [6]:
X = cancer.drop(['Class'],axis=1)

In [7]:
y = cancer['Class']

#Train And Test Splitting

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(455, 30) (114, 30) (455,) (114,)


#Feature Scaling

In [9]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)

#Model

In [10]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)

SVC()

In [12]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import classification_report

y_train_pred = model.predict(X_train)

print("Metrics on Train samples")
print("============================================================== ")
print("confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
print("classification_report: \n",classification_report(y_train,y_train_pred))
print("============================================================== ")

y_test_pred = model.predict(X_test)

print("Metrics on Test samples ")
print("============================================================== ")
print("confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
print("classification_report: \n",classification_report(y_test,y_test_pred))
print("============================================================== ")

Metrics on Train samples
confusion_matrix: 
 [[286   0]
 [  5 164]]
classification_report: 
               precision    recall  f1-score   support

           1       0.98      1.00      0.99       286
           2       1.00      0.97      0.98       169

    accuracy                           0.99       455
   macro avg       0.99      0.99      0.99       455
weighted avg       0.99      0.99      0.99       455

Metrics on Test samples 
confusion_matrix: 
 [[71  0]
 [ 2 41]]
classification_report: 
               precision    recall  f1-score   support

           1       0.97      1.00      0.99        71
           2       1.00      0.95      0.98        43

    accuracy                           0.98       114
   macro avg       0.99      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



#k-Fold Cross Validation

In [13]:
# Applying k-Fold Cross Validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = model, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

0.971400966183575
0.029891477577207518


#SVM with Sigmoid

In [14]:
from sklearn.svm import SVC
models = SVC(kernel = 'sigmoid')
models.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [16]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import classification_report

y_train_pred = model.predict(X_train)

print("Metrics on Train samples")
print("============================================================== ")
print("confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
print("classification_report: \n",classification_report(y_train,y_train_pred))
print("============================================================== ")

y_test_pred = model.predict(X_test)

print("Metrics on Test samples ")
print("============================================================== ")
print("confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
print("classification_report: \n",classification_report(y_test,y_test_pred))
print("============================================================== ")

Metrics on Train samples
confusion_matrix: 
 [[286   0]
 [  5 164]]
classification_report: 
               precision    recall  f1-score   support

           1       0.98      1.00      0.99       286
           2       1.00      0.97      0.98       169

    accuracy                           0.99       455
   macro avg       0.99      0.99      0.99       455
weighted avg       0.99      0.99      0.99       455

Metrics on Test samples 
confusion_matrix: 
 [[71  0]
 [ 2 41]]
classification_report: 
               precision    recall  f1-score   support

           1       0.97      1.00      0.99        71
           2       1.00      0.95      0.98        43

    accuracy                           0.98       114
   macro avg       0.99      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



#SVC with polynomial kernel

In [17]:
models = SVC(kernel = 'poly')
models.fit(X_train, y_train)

SVC(kernel='poly')

In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import classification_report

y_train_pred = model.predict(X_train)

print("Metrics on Train samples")
print("============================================================== ")
print("confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
print("classification_report: \n",classification_report(y_train,y_train_pred))
print("============================================================== ")

y_test_pred = model.predict(X_test)

print("Metrics on Test samples ")
print("============================================================== ")
print("confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
print("classification_report: \n",classification_report(y_test,y_test_pred))
print("============================================================== ")

Metrics on Train samples
confusion_matrix: 
 [[286   0]
 [  5 164]]
classification_report: 
               precision    recall  f1-score   support

           1       0.98      1.00      0.99       286
           2       1.00      0.97      0.98       169

    accuracy                           0.99       455
   macro avg       0.99      0.99      0.99       455
weighted avg       0.99      0.99      0.99       455

Metrics on Test samples 
confusion_matrix: 
 [[71  0]
 [ 2 41]]
classification_report: 
               precision    recall  f1-score   support

           1       0.97      1.00      0.99        71
           2       1.00      0.95      0.98        43

    accuracy                           0.98       114
   macro avg       0.99      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



#SVC Kernel Linear With Degree 2

In [19]:
model = SVC(kernel='linear',degree=2)
model.fit(X_train,y_train)

SVC(degree=2, kernel='linear')

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import classification_report

y_train_pred = model.predict(X_train)

print("Metrics on Train samples")
print("============================================================== ")
print("confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
print("classification_report: \n",classification_report(y_train,y_train_pred))
print("============================================================== ")

y_test_pred = model.predict(X_test)

print("Metrics on Test samples ")
print("============================================================== ")
print("confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
print("classification_report: \n",classification_report(y_test,y_test_pred))
print("============================================================== ")

Metrics on Train samples
confusion_matrix: 
 [[283   3]
 [  3 166]]
classification_report: 
               precision    recall  f1-score   support

           1       0.99      0.99      0.99       286
           2       0.98      0.98      0.98       169

    accuracy                           0.99       455
   macro avg       0.99      0.99      0.99       455
weighted avg       0.99      0.99      0.99       455

Metrics on Test samples 
confusion_matrix: 
 [[68  3]
 [ 2 41]]
classification_report: 
               precision    recall  f1-score   support

           1       0.97      0.96      0.96        71
           2       0.93      0.95      0.94        43

    accuracy                           0.96       114
   macro avg       0.95      0.96      0.95       114
weighted avg       0.96      0.96      0.96       114



#SVM with GridSearchCV

In [ ]:
from sklearn.model_selection import GridSearchCV

parameters = {'kernel':['linear', 'rbf','sigmoid','poly'], 'C':[1, 10,100],'gamma' : [1,10,100],'degree':[1,10,100]}
clf = GridSearchCV(models, parameters, cv=5)

clf.fit(X_train, y_train)

In [ ]:
print(clf.best_params_)