In [8]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [9]:
df = pd.read_csv('cardiotocography.csv')

In [10]:
df.head()

V1   V2    V3   V4   V5  V6  V7  ...  V30  V31  V32  V33  V34  V35  Class
0  23  240   357  120  120   0   0  ...    0    0    0    0    1    0      9
1  45    5   632  132  132   4   0  ...    0    1    0    0    0    0      6
2  45  177   779  133  133   2   0  ...    0    1    0    0    0    0      6
3  45  411  1192  134  134   2   0  ...    0    1    0    0    0    0      6
4  45  533  1147  132  132   4   0  ...    0    0    0    0    0    0      2

[5 rows x 36 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 36 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      2126 non-null   int64  
 1   V2      2126 non-null   int64  
 2   V3      2126 non-null   int64  
 3   V4      2126 non-null   int64  
 4   V5      2126 non-null   int64  
 5   V6      2126 non-null   int64  
 6   V7      2126 non-null   int64  
 7   V8      2126 non-null   int64  
 8   V9      2126 non-null   int64  
 9   V10     2126 non-null   float64
 10  V11     2126 non-null   int64  
 11  V12     2126 non-null   float64
 12  V13     2126 non-null   int64  
 13  V14     2126 non-null   int64  
 14  V15     2126 non-null   int64  
 15  V16     2126 non-null   int64  
 16  V17     2126 non-null   int64  
 17  V18     2126 non-null   int64  
 18  V19     2126 non-null   int64  
 19  V20     2126 non-null   int64  
 20  V21     2126 non-null   int64  
 21  V22     2126 non-null   int64  
 22  

In [12]:
df['Class'].value_counts()

2     579
1     384
6     332
7     252
10    197
8     107
4      81
5      72
9      69
3      53
Name: Class, dtype: int64

In [13]:
X = df.drop(['Class'],axis=1)

In [14]:
y = df['Class']

#Train And Test Splitting

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(1700, 35) (426, 35) (1700,) (426,)


#Models

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from xgboost import  XGBClassifier 

from sklearn.metrics import confusion_matrix,classification_report

In [26]:
Model_list = [LogisticRegression(),KNeighborsClassifier(),SVC(),DecisionTreeClassifier()]

In [27]:
for mod in range(len(Model_list)):
  model = Model_list[mod]

  
  model.fit(X_train,y_train)

  y_train_pred = model.predict(X_train)
  print("Model Used : ",model)
  print("=======================================================================")
  print("Metrics on Train samples")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
  print("classification_report: \n",classification_report(y_train,y_train_pred))
  print("============================================================== ")

  y_test_pred = model.predict(X_test)

  print("Metrics on Test samples ")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
  print("classification_report: \n",classification_report(y_test,y_test_pred))
  print("============================================================== ")
  print("=======================================================================")

Model Used :  LogisticRegression()
Metrics on Train samples
confusion_matrix: 
 [[198  91   2   1   0   4   4   0   0  11]
 [ 70 334   0   1   0  46  14   0   0   0]
 [  6  28   4   0   0   0   2   0   0   0]
 [  3  28   1   3   0  23   4   0   0   0]
 [ 30  21   0   0   0   2   0   0   0   2]
 [  0  73   1   1   0 159  27   8   0   0]
 [  6  47   3   3   0  60  76   3   0   0]
 [  0   1   0   0   0   2  14  74   0   0]
 [ 14   3   1   0   0   0   0   0   5  34]
 [ 91  17   0   0   0   0   6   0   2  36]]
classification_report: 
               precision    recall  f1-score   support

           1       0.47      0.64      0.54       311
           2       0.52      0.72      0.60       465
           3       0.33      0.10      0.15        40
           4       0.33      0.05      0.08        62
           5       0.00      0.00      0.00        55
           6       0.54      0.59      0.56       269
           7       0.52      0.38      0.44       198
           8       0.87      0.

In [28]:
NB_Model_list = [GaussianNB(),BernoulliNB()]

In [29]:
for mod in range(len(NB_Model_list)):
  model = NB_Model_list[mod]
  #print(model)
  
  model.fit(X_train,y_train)

  y_train_pred = model.predict(X_train)
  print("Model Used : ",model)
  print("=======================================================================")
  print("Metrics on Train samples")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
  print("classification_report: \n",classification_report(y_train,y_train_pred))
  print("============================================================== ")

  y_test_pred = model.predict(X_test)

  print("Metrics on Test samples ")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
  print("classification_report: \n",classification_report(y_test,y_test_pred))
  print("============================================================== ")
  print("=======================================================================")

Model Used :  GaussianNB()
Metrics on Train samples
confusion_matrix: 
 [[311   0   0   0   0   0   0   0   0   0]
 [  0 465   0   0   0   0   0   0   0   0]
 [  0   0  40   0   0   0   0   0   0   0]
 [  0   0   0  62   0   0   0   0   0   0]
 [  0   0   0   0  55   0   0   0   0   0]
 [  0   0   0   0   0 269   0   0   0   0]
 [  0   0   0   0   0   0 198   0   0   0]
 [  0   0   0   0   0   0   0  91   0   0]
 [  0   0   0   0   0   0   0   0  57   0]
 [  0   0   0   0   0   0   0   0   0 152]]
classification_report: 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00       311
           2       1.00      1.00      1.00       465
           3       1.00      1.00      1.00        40
           4       1.00      1.00      1.00        62
           5       1.00      1.00      1.00        55
           6       1.00      1.00      1.00       269
           7       1.00      1.00      1.00       198
           8       1.00      1.00      

In [30]:
ensemble_Model_list = [BaggingClassifier(),GradientBoostingClassifier(),AdaBoostClassifier(),RandomForestClassifier(),ExtraTreesClassifier()]

In [31]:
for mod in range(len(ensemble_Model_list)):
  model = ensemble_Model_list[mod]
  #print(model)
  
  model.fit(X_train,y_train)

  y_train_pred = model.predict(X_train)
  print("Model Used : ",model)
  print("=======================================================================")
  print("Metrics on Train samples")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_train,y_train_pred))
  print("classification_report: \n",classification_report(y_train,y_train_pred))
  print("============================================================== ")

  y_test_pred = model.predict(X_test)

  print("Metrics on Test samples ")
  print("============================================================== ")
  print("confusion_matrix: \n",confusion_matrix(y_test,y_test_pred))
  print("classification_report: \n",classification_report(y_test,y_test_pred))
  print("============================================================== ")
  print("=======================================================================")

Model Used :  BaggingClassifier()
Metrics on Train samples
confusion_matrix: 
 [[311   0   0   0   0   0   0   0   0   0]
 [  0 465   0   0   0   0   0   0   0   0]
 [  0   0  40   0   0   0   0   0   0   0]
 [  0   0   0  62   0   0   0   0   0   0]
 [  0   0   0   0  55   0   0   0   0   0]
 [  0   0   0   0   0 269   0   0   0   0]
 [  0   0   0   0   0   0 198   0   0   0]
 [  0   0   0   0   0   0   0  91   0   0]
 [  0   0   0   0   0   0   0   0  57   0]
 [  0   0   0   0   0   0   0   0   0 152]]
classification_report: 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00       311
           2       1.00      1.00      1.00       465
           3       1.00      1.00      1.00        40
           4       1.00      1.00      1.00        62
           5       1.00      1.00      1.00        55
           6       1.00      1.00      1.00       269
           7       1.00      1.00      1.00       198
           8       1.00      1.0